# __init__.py

from .wan_video_extender import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_1
from .wan_video_extender import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_1

from .wan_video_extender_low_high import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2
from .wan_video_extender_low_high import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2


NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_1,
    **NODE_CLASS_MAPPINGS_2,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_1,
    **NODE_DISPLAY_NAME_MAPPINGS_2,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']